-- FETCH 7 PRIMERAS FILAS
SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC FETCH FIRST 7 ROWS ONLY;

-- FETCH TIES SI HAY OTRA FILA QUE CUMPLE LA CONDICION DE LA ULTIMA, TAMBIEN LA MUESTRA
-- NANCY Y SHELLEY TIENEN EL MISMO SALARIO
SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC FETCH FIRST 7 ROWS WITH TIES;

-- OFFSET SE SALTA N FILAS EMPIEZA DESDE LA 6TA, TOMANDO COMO BASE LA ANTERIOR EMPIEZA EN MICHAEL.
SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC OFFSET 5 ROWS FETCH FIRST 7 ROWS WITH TIES;

-- MUESTRA EL PRIMER 20% DE LAS FILAS (107 REGISTROS, RECUPERA 22 FILAS)
SELECT * FROM EMPLOYEES FETCH FIRST 20 PERCENT ROWS ONLY;