--FUNCIONES
--LOWER, CONVIERTE A MINUSCULAS
SELECT EMAIL, LOWER(EMAIL) FROM EMPLOYEES;

--UPPER CONVIERTE A MAYUSCULAS
SELECT FIRST_NAME, LOWER(FIRST_NAME) FROM EMPLOYEES;

--INITCAP, PRIMER LETRA DE CADA PALABRA EN MAYUSCULAS
SELECT INITCAP('ESTO ES UNA PRUEBA') FROM DUAL;