--FUNCIONES DEL WHERE
SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE UPPER(FIRST_NAME)='DAVID';

-- CONCAT, CONCATENA CADENAS
SELECT CONCAT(FIRST_NAME, CONCAT(' ', LAST_NAME)) FROM EMPLOYEES;

-- SUBSTR(CADENA,POSICION, LONGITUD),  SUBCADENA DE UNA CADENA
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 1, 3) FROM EMPLOYEES;

-- SUBSTR(CADENA,POSICION, LONGITUD),  SUBCADENA DE UNA CADENA
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 3) FROM EMPLOYEES;

-- SUBSTR(CADENA,POSICION, LONGITUD),  ULTIMO CARACTER DE UNA CADENA
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, LENGTH(FIRST_NAME), 1) FROM EMPLOYEES;

-- LENGTH 
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES;

-- LENGTH 
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME)=6;

-- INSTR(C1, C2) POSICION QUE OCUPA UNA CADENA, DENTRO DE OTRA CADENA
SELECT FIRST_NAME, INSTR(FIRST_NAME, 'a') FROM EMPLOYEES;

-- INSTR(C1, C2) POSICION QUE OCUPA UNA CADENA, DENTRO DE OTRA CADENA
SELECT FIRST_NAME, INSTR( LOWER(FIRST_NAME), 'a') FROM EMPLOYEES
WHERE INSTR( LOWER(FIRST_NAME), 'a') <> 0;

-- RPAD, RELLENA CARACTERES A LA DERECHA
SELECT RPAD(FIRST_NAME, 20, '*') FROM EMPLOYEES;

-- LPAD, RELLENA CARACTERES A LA IZQUIERDA
SELECT LPAD(FIRST_NAME, 20, '*') FROM EMPLOYEES; 

-- REPLACE , REEMPLAZA CARACTERES
SELECT REPLACE(FIRST_NAME, 'a', '*') FROM EMPLOYEES; 

--RTRIM ELIMINAR CARACTERES POR LA DERECHA
SELECT RTRIM('ELIEL         ')||RTRIM(' ADIOS') FROM DUAL;

--LTRIM ELIMINAR CARACTERES POR LA IZQUIERDA
SELECT LTRIM('     ELIEL')||RTRIM(' ADIOS     ') FROM DUAL;


-- 1. Funciones carácter
--  En la tabla LOCATIONS, averiguar las ciudades que son de Canada o Estados unidos 
-- (Country_id=CA o US) y que la longitud del nombre de la calle sea superior a 15.
SELECT CITY, STREET_ADDRESS, COUNTRY_ID FROM LOCATIONS
WHERE COUNTRY_ID IN ('CA', 'US') AND LENGTH(STREET_ADDRESS)>15;


-- Muestra la longitud del nombre y el salario anual (por 14) 
-- para los empleados cuyo apellido contenga el carácter 'b' después de la 3ª posición.
SELECT FIRST_NAME, LENGTH(FIRST_NAME), SALARY*14 AS SALARIOANUAL , LAST_NAME FROM EMPLOYEES
WHERE INSTR(LAST_NAME, 'b') > 3;

-- Averiguar los empleados que ganan entre 4000 y 7000 euros y que tienen alguna 'a' en el nombre. 
-- (Debemos usar INSTR y da igual que sea mayúscula que minúsculas) y que tengan comisión.
SELECT * FROM EMPLOYEES
WHERE INSTR(UPPER(FIRST_NAME), 'A')<>0 AND SALARY BETWEEN 4000 AND 7000 AND commission_pct IS NOT NULL;

-- Visualizar las iniciales de nombre y apellidos separados por puntos. Por ejemplo: E.A, T.N
SELECT FIRST_NAME, LAST_NAME, CONCAT(CONCAT(SUBSTR(FIRST_NAME, 1,1),'.') , CONCAT(SUBSTR(LAST_NAME, 1,1),'.')) AS INICIALES FROM EMPLOYEES;

-- Mostrar empleados donde el nombre o apellido comienza con S..
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%' OR LAST_NAME LIKE 'S%'

-- Visualizar el nombre del empleado, su salario, y con asteriscos, el número miles de dólares que gana. 
-- Se asocia ejemplo. (PISTA: se puede usar RPAD. Ordenado por salario,  RPAD(FIRST_NAME, 20, '*')

SELECT FIRST_NAME, LAST_NAME, SALARY, RPAD(' ', (SALARY/1000)+1, '*') FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT FIRST_NAME, LAST_NAME, SALARY, RPAD('*', (SALARY/1000), '*') FROM EMPLOYEES ORDER BY SALARY DESC;






