--FUNCIONES DE TIPO NUMERICO

--ROUND, REDONDEAR UNA CANTIDAD
SELECT ROUND(50.900, 2) FROM DUAL;
SELECT ROUND(50.9084545, 2) FROM DUAL;

--TRUNC,  TRUNCAR UNA CANTIDAD
SELECT TRUNC(50.900, 2) FROM DUAL;
SELECT TRUNC(50.94545, 2) FROM DUAL;

--MOD, MODULO DE UNA DIVISION
SELECT MOD(10, 3) FROM DUAL;

--POWER, ELEVA A UNA POTENCIA
SELECT POWER(10, 3) FROM DUAL;


-- 1. Funciones numéricas
-- Visualizar el nombre y salario de los empleados de los que el número de empleado es impar (PISTA: MOD)
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2)<> 0;


-- Prueba con los siguientes valores aplicando las funciones TRUNC y ROUND, con 1 y 2 decimales.
SELECT TRUNC(25.67, 0), ROUND(25.67, 0) FROM DUAL;
SELECT TRUNC(25.67, 1), ROUND(25.67, 1) FROM DUAL;
SELECT TRUNC(25.34,0), ROUND(25.34,0) FROM DUAL;
SELECT TRUNC(25.34,1), ROUND(25.34,1) FROM DUAL;
SELECT TRUNC(25.67,-1), ROUND(25.67,-1) FROM DUAL;