-- ARITMETICA & FUNCIONES DE FECHA
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES;

-- FECHA ACTUAL DEL SISTEMA. AÑO JULIANO 1 ENERO -4712 AC
SELECT SYSDATE FROM DUAL;

-- SUMAR/RESTAR UN NUMERO DE DIAS
SELECT SYSDATE+2, SYSDATE-2 FROM DUAL;

-- NUMERO DE DIAS/SEMANAS DESDE LA FECHA DE CONTRATACION
SELECT HIRE_DATE, SYSDATE-HIRE_DATE AS DIAS,  (SYSDATE-HIRE_DATE)/7 AS SEMANAS FROM EMPLOYEES;

-- MONTHS_BETWEEN, NUMERO DE MESES ENTRE DOS FECHAS.
SELECT MONTHS_BETWEEN(SYSDATE, HIRE_DATE) FROM EMPLOYEES;

-- ADD_MONTHS AÑADE MESES DE CALENDARIO A UNA FECHA, TOMA EN CUENTA EL NUMERO DE DIAS QUE TIENE CADA MES.
SELECT SYSDATE, ADD_MONTHS(SYSDATE, 3), SYSDATE+90 FROM DUAL;

-- NEXT_DAY , FECHA DEL PROXIMO MIERCOLES
-- ALTER SESSION SET NLS_DATE_LANGUAGE = 'ENGLISH';  SETEAR EL IDIOMA PARA LAS FECHAS
SELECT NEXT_DAY(SYSDATE, 'MIÉRCOLES') FROM DUAL;

-- LAST_DAY , ULTIMO DÍA DEL MES
SELECT SYSDATE, LAST_DAY(SYSDATE), LAST_DAY('10-06-23') FROM DUAL;

--ROUND REDONDEA AL MES O AÑO
SELECT SYSDATE, ROUND(SYSDATE, 'MONTH'), ROUND(SYSDATE, 'YEAR') FROM DUAL;

-- TRUNC TRUNCA AL MES O AÑO
SELECT SYSDATE, TRUNC(SYSDATE, 'MONTH'), TRUNC(SYSDATE, 'YEAR') FROM DUAL;


-- 1. Funciones de fecha
-- Indicar el número de días que los empleados llevan en la empresa
SELECT FIRST_NAME, HIRE_DATE, ROUND(SYSDATE-HIRE_DATE) AS DIAS FROM EMPLOYEES;

-- Indicar la fecha que será dentro de 15 días
SELECT SYSDATE, SYSDATE+15 AS FECHA_15_DIAS FROM DUAL;

-- ¿Cuántos MESES faltan para la navidad? La cifra debe salir redondeada, con 1 decimal
SELECT ROUND(MONTHS_BETWEEN('24-12-23', SYSDATE), 1) FROM DUAL;

-- Indicar la fecha de entrada de un empleado y el último día del mes que entró
SELECT FIRST_NAME, HIRE_DATE, LAST_DAY(HIRE_DATE) AS DIAS FROM EMPLOYEES;


-- Utilizando la función ROUND, indicar los empleados que entraron en los últimos 15 días de cada mes
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE ROUND(HIRE_DATE, 'MONTH') > HIRE_DATE;

SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE LAST_DAY(HIRE_DATE)-HIRE_DATE < 15;
