-- NVL(EXPRESION, VALOR) MANEJO DE NULOS
SELECT NVL('HOLA', 'ADIOS')  FROM DUAL;
SELECT NVL(NULL, 'ADIOS')  FROM DUAL;

SELECT FIRST_NAME, COMMISSION_PCT, NVL(COMMISSION_PCT, 0) FROM EMPLOYEES;

-- NVL2(EXPRESION, VALOR1(SI EXPRESION NO ES NULO), VALOR2(SI EXPRESION ES NULO)) MANEJO DE NULOS
SELECT FIRST_NAME, COMMISSION_PCT, NVL2(COMMISSION_PCT, SALARY*COMMISSION_PCT, 0) FROM EMPLOYEES;

-- NULLIF(V1, V2), SI V1 == V2 DEVUELVE NULL,  SI V1 != V2 DEVUELVE V1
SELECT NULLIF(1,1), NULLIF(1,10) FROM DUAL;

-- NULO CUANDO COINCIDAN LAS 2 PRIMERAS LETRAS DEL NOMBRE CON EL CODIGO DEL PAIS
SELECT COUNTRY_ID, COUNTRY_NAME, NULLIF(COUNTRY_ID, UPPER(SUBSTR(COUNTRY_NAME, 1,2))) FROM COUNTRIES;


--COALESCE(V1, V2, V3, V4,.....), CUANDO ENCUENTRA EL PRIMER VALOR NO NULO, LO DEVUELVE, Y NO EVALUA LOS DEMAS
SELECT COALESCE('VALOR1','VALOR2','VALOR3'), COALESCE(NULL,'VALOR2','VALOR3') FROM DUAL;

SELECT FIRST_NAME, TO_CHAR(COMMISSION_PCT), TO_CHAR(MANAGER_ID) FROM EMPLOYEES;
SELECT FIRST_NAME, COALESCE(TO_CHAR(COMMISSION_PCT), TO_CHAR(MANAGER_ID), 'SIN JEFE NI COMISION')  FROM EMPLOYEES;


-- 1. FUNCIONES DE NULOS
-- De la tabla LOCATIONS visualizar el nombre de la ciudad y el estado-provincia. En el caso de que no tenga que aparezca el texto “No tiene”
SELECT CITY, STATE_PROVINCE, NVL(STATE_PROVINCE, 'NO TIENE') FROM LOCATIONS;

-- Visualizar el salario de los empleados incrementado en la comisión (PCT_COMMISSION). Si no tiene comisión solo debe salir el salario
SELECT FIRST_NAME,  NVL2(COMMISSION_PCT,  SALARY+(COMMISSION_PCT*SALARY), SALARY) FROM EMPLOYEES;

-- Seleccionar el nombre del departamento y el manager_id. Si no tiene, debe salir un -1
SELECT DEPARTMENT_NAME, NVL(MANAGER_ID, -1) FROM DEPARTMENTS;

-- De la tabla LOCATIONS, devolver NULL si la ciudad y la provincia son iguales. Si no son iguales devolver la CITY.
-- NULLIF(V1, V2), SI V1 == V2 DEVUELVE NULL,  SI V1 != V2 DEVUELVE V1
SELECT CITY, STATE_PROVINCE, NULLIF(CITY, STATE_PROVINCE) FROM LOCATIONS;