-- FUNCIONES DE GRUPO , AGRUPACIONES
-- LAS FUNCIONES DE GRUPO , NO SE MEZCLAN CON COLUMNAS SIMPLES, SOLO SINO APARECEN EN EL GROUP BY
-- AVG (NUMERO)  , PROMEDIO
SELECT AVG(SALARY) FROM EMPLOYEES;

-- MAX (NUMERO)  , MAXIMO
SELECT MAX(SALARY) FROM EMPLOYEES;

-- MIN (NUMERO)  , MINIMO
SELECT MIN(SALARY) FROM EMPLOYEES;

-- NUMERICOS 
SELECT AVG(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=50;

-- TIPO DATE, AVG(DATE) NO VALIDO
SELECT MAX(HIRE_DATE), MIN(HIRE_DATE) FROM EMPLOYEES WHERE DEPARTMENT_ID=50;

-- TIPO STRING, AVG(STRING) NO VALIDO
SELECT MAX(FIRST_NAME), MIN(FIRST_NAME) FROM EMPLOYEES WHERE DEPARTMENT_ID=50;

-- COUNT(VALOR)  CUENTA TODO, DUPLICADOS, NO CUENTA NULOS
SELECT COUNT(EMPLOYEE_ID), COUNT(FIRST_NAME), COUNT(SALARY), COUNT(COMMISSION_PCT) FROM EMPLOYEES WHERE DEPARTMENT_ID=50;

-- CUENTA DISTINTOS
SELECT COUNT(DISTINCT FIRST_NAME) FROM EMPLOYEES;

-- SUM(VALOR) SUMAR VALORES
SELECT SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=50;

