-- GROUP BY
-- AGRUPAR VALORES POR GRUPOS 
SELECT DEPARTMENT_ID, FIRST_NAME  FROM EMPLOYEES GROUP BY DEPARTMENT_ID, FIRST_NAME;

-- TOTAL DE SALARIOS, NUMERO DE EMPLEADOS POR ID DE DEPARTAMENTO
SELECT  DEPARTMENT_ID, COUNT(*) AS NO_EMPLEADOS, SUM(SALARY) AS SALARIOS_DEPTOS
FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

-- TOTAL DE SALARIOS, NUMERO DE EMPLEADOS POR ID DE DEPARTAMENTO Y JOB_ID
SELECT  DEPARTMENT_ID, JOB_ID, COUNT(*) AS NO_EMPLEADOS, SUM(SALARY) AS SALARIOS_DEPTOS
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID, JOB_ID 
ORDER BY DEPARTMENT_ID;


-- HAVING ES EL WHERE DEL GROUP BY
-- EN EL HAVING SIEMPRE DEBE LLEVAR FUNCIONES DE GRUPO
-- EL WHERE FUNCIONA CON FILAS CONCRETAS

-- TOTAL DE SALARIOS, NUMERO DE EMPLEADOS POR ID DE DEPARTAMENTO Y JOB_ID, Y QUE EL SALARIO DEL GRUPO SEA MAYOR A 25,000 Y TENGA MAS DE 10 EMPLEADOS
SELECT  DEPARTMENT_ID, JOB_ID, COUNT(*) AS NO_EMPLEADOS, SUM(SALARY) AS SALARIOS_DEPTOS
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID, JOB_ID 
HAVING SUM(SALARY) > 25000 AND COUNT(*) >10
ORDER BY DEPARTMENT_ID;



-- 1. Funciones de grupo
-- Indicar el número de empleados del departamento 50
SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

-- Indicar el número de empleados que entraron en el año 2007 a trabajar
SELECT COUNT(*) FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'YYYY')=2007;

-- Indicar la diferencia entre el sueldo más alto y al mínimo
SELECT MAX(SALARY), MIN(SALARY), MAX(SALARY)-MIN(SALARY) AS DIFERENCIA_SALARIOS FROM EMPLOYEES;

-- Visualizar la suma del salario del departamento 100
SELECT SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=100;

-- Mostrar el salario medio por departamento, con dos decimales
SELECT DEPARTMENT_ID, TO_CHAR(AVG(SALARY), 'L99999.99') AS SALARIO_PROMEDIO FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

-- Mostrar el country_id y el número de ciudades que hay en ese país.
SELECT COUNTRY_ID, COUNT(*) FROM LOCATIONS
GROUP BY COUNTRY_ID
ORDER BY COUNTRY_ID;

-- Mostrar el promedio de salario de los empleados por departamento que tengan comisión
SELECT DEPARTMENT_ID, TO_CHAR(AVG(SALARY), 'L99999.99') AS PROMEDIO_DEPTO FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

-- Mostrar los años en que ingresaron más de 10 empleados
SELECT  TO_CHAR(HIRE_DATE, 'YYYY') AS ANIO, COUNT(*) FROM EMPLOYEES 
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
HAVING COUNT(*) >10
ORDER BY ANIO;

-- Mostrar por departamento y año el número de empleados que ingresaron
SELECT  DEPARTMENT_ID, TO_CHAR(HIRE_DATE, 'YYYY') AS ANIO, COUNT(EMPLOYEE_ID) FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID, TO_CHAR(HIRE_DATE, 'YYYY')
ORDER BY DEPARTMENT_ID, ANIO;


-- Mostrar los departament_id de los departamentos que tienen managers que tienen a cargo más de 5 empleados
SELECT  DISTINCT DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, MANAGER_ID
HAVING COUNT(EMPLOYEE_ID) >5
ORDER BY DEPARTMENT_ID;

