-- NATURAL JOINS
-- BUSCA COLUMNAS QUE SE LLAMEN IGUAL EN AMBAS TABLAS PK=FK,
-- SI EXISTEN CAMPOS QUE SE LLAMEN IGUAL CAUSARA PROBLEMAS(NAME(region) vs NAME(country))
-- CREA UNA NUEVA TABLA TEMPORAL

SELECT * FROM COUNTRIES;
SELECT * FROM REGIONS;

SELECT * FROM REGIONS NATURAL JOIN COUNTRIES;

-- ESTO CAUSA UN ERROR, EL LA PONE DE MANERA AUTOMATICA, LA COLUMNA DE CRUZE
SELECT R.REGION_ID, C.REGION_ID, REGION_NAME, COUNTRY_ID, COUNTRY_NAME
FROM REGIONS R NATURAL JOIN COUNTRIES C;

-- OK
SELECT REGION_ID, REGION_NAME, COUNTRY_ID, COUNTRY_NAME
FROM REGIONS R NATURAL JOIN COUNTRIES C;

-- OK
SELECT REGION_NAME, COUNTRY_NAME
FROM REGIONS R NATURAL JOIN COUNTRIES C;

