-- CLAUSULA USING
-- LAS COLUMNAS LAS ESPECIFICO YO

-- 106 REGISTROS OK
SELECT DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME 
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    USING(DEPARTMENT_ID);

-- 57 REGISTROS OK
SELECT DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME 
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    USING(DEPARTMENT_ID)
    WHERE SALARY > 5000;

-- ¡¡ ERROR !!  32 REGISTROS EL CONFLICTO LO OCASIONA LA COLUMNA MANAGER_ID, APARECE EN AMBAS TABLAS ¡¡ ERROR !! 
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME 
FROM EMPLOYEES E NATURAL JOIN DEPARTMENTS D;

