-- CLAUSULA ON

-- USING, SE PUEDE USAR SIEMPRE QUE SE LLAMEN IGUAL
SELECT DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME 
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    USING(DEPARTMENT_ID)
    WHERE SALARY > 5000;
    
-- ON
SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME 
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
    WHERE SALARY > 5000;
    
-- ON PUEDE TENER MAS DE UNO
SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME, CITY
    FROM EMPLOYEES E JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
                     JOIN LOCATIONS L ON (L.LOCATION_ID=D.LOCATION_ID)   
    WHERE SALARY > 5000;
    
    
-- EMPLEADOS CON LOS DEPARTAMENTOS EN LOS QUE NO TRABAJA
SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME 
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON(E.DEPARTMENT_ID<>D.DEPARTMENT_ID)
    WHERE SALARY > 5000;