-- CLAUSULA WITH
-- SIMPLIFICAR SUBCONSULTAS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME , SUM(SALARY) AS SALARIO
    FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
    HAVING SUM(SALARY) > 20000
     GROUP BY DEPARTMENT_ID, DEPARTMENT_NAME;
     
-- OTRA FORMA DE HACER LO MISMO , CON WITH
-- COMO CREAR UNA TABLA TEMPORAL
WITH SUMA_SALARIOS AS (SELECT DEPARTMENT_ID, SUM(SALARY) AS SALARIO FROM EMPLOYEES GROUP BY DEPARTMENT_ID)
SELECT 
	DEPARTMENT_ID,  DEPARTMENT_NAME, SALARIO 
FROM 
	SUMA_SALARIOS NATURAL JOIN DEPARTMENTS
WHERE 
	SALARIO > 20000;


-- OTRO EJEMPLO
-- PERMITE CREAR 2 TABLAS TEMPORALES
WITH 
    SUMA_SALARIOS AS (SELECT DEPARTMENT_ID, SUM(SALARY) AS SALARIOS FROM EMPLOYEES GROUP BY DEPARTMENT_ID),
    NUM_EMPLEADOS AS (SELECT DEPARTMENT_ID, COUNT(*) AS EMPLEADOS FROM EMPLOYEES GROUP BY DEPARTMENT_ID)
SELECT 
    DEPARTMENT_NAME, SALARIOS, EMPLEADOS
FROM 
    DEPARTMENTS, SUMA_SALARIOS, NUM_EMPLEADOS
WHERE
    DEPARTMENTS.DEPARTMENT_ID = SUMA_SALARIOS.DEPARTMENT_ID AND 
    DEPARTMENTS.DEPARTMENT_ID = NUM_EMPLEADOS.DEPARTMENT_ID AND
    EMPLEADOS < 10;
